import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Boxes, ChartNoAxesCombined, ClipboardList, ContactRound, FileText, LayoutDashboard, LogOut, Menu, MessageCircle, Package, RefreshCw, Search, ShieldCheck, Tags, Users, X } from 'lucide-react';
import { HubConnectionBuilder, HttpTransportType, LogLevel } from '@microsoft/signalr';
import './styles.css';

const modules = [
  { id: 'dashboard', title: 'لوحة التحكم', icon: LayoutDashboard },
  { id: 'orders', title: 'الطلبات', icon: ClipboardList },
  { id: 'products', title: 'المنتجات', icon: Package },
  { id: 'categories', title: 'التصنيفات', icon: Tags },
  { id: 'batches', title: 'المخزون والتشغيلات', icon: Boxes },
  { id: 'customers', title: 'العملاء', icon: ContactRound },
  { id: 'invoices', title: 'فواتير المبيعات', icon: FileText },
  { id: 'users', title: 'المستخدمون والصلاحيات', icon: Users },
  { id: 'chats', title: 'دعم العملاء', icon: MessageCircle }
];
const roles = { SuperAdmin: 'مدير عام', Admin: 'مدير', Pharmacist: 'صيدلي', Customer: 'عميل' };
const definitions = {
  orders: { title: 'الطلبات', endpoint: '/api/Admin/Orders', fields: [['orderNumber','رقم الطلب'],['orderDate','التاريخ'],['status','الحالة'],['isPaid','مدفوع'],['netAmount','الصافي'],['paymentMethod','الدفع']], detail: true },
  products: { title: 'المنتجات', endpoint: '/api/Admin/Products/get', fields: [['name','المنتج'],['genericName','الاسم العلمي'],['categoryName','التصنيف'],['price','السعر'],['minStockLevel','حد المخزون'],['requiresPrescription','روشتة']], editable: true },
  categories: { title: 'التصنيفات', endpoint: '/api/Admin/Categories', fields: [['id','المعرف'],['name','التصنيف']], editable: true },
  batches: { title: 'المخزون والتشغيلات', endpoint: '/api/Admin/Batches', fields: [['batchNumber','رقم التشغيلة'],['productName','المنتج'],['expiryDate','الصلاحية'],['quantityOnHand','المتاح'],['costPrice','التكلفة']], editable: true },
  customers: { title: 'العملاء', endpoint: '/api/Admin/Customer/get', fields: [['name','الاسم'],['phone','الهاتف'],['currentBalance','الرصيد']], editable: true },
  invoices: { title: 'فواتير المبيعات', endpoint: '/api/Admin/SalesInvoices/get', fields: [['invoiceNumber','رقم الفاتورة'],['invoiceDate','التاريخ'],['totalAmount','الإجمالي'],['discount','الخصم'],['netAmount','الصافي']], detail: true },
  users: { title: 'المستخدمون والصلاحيات', endpoint: '/api/Admin/Users', fields: [['firstName','الاسم الأول'],['lastName','اسم العائلة'],['email','البريد'],['phoneNumber','الهاتف'],['roles','الأدوار'],['isLocked','الحساب']], editable: true },
  chats: { title: 'دعم العملاء', endpoint: '/api/Admin/Chat', fields: [['customerName','العميل'],['lastMessageAt','آخر رسالة'],['unreadMessages','غير مقروء']], detail: true }
};
const canManage = r => r.includes('SuperAdmin') || r.includes('Admin');
const unwrap = body => body?.data ?? body;
const fmt = value => {
  if (value == null || value === '') return '—';
  if (typeof value === 'boolean') return value ? 'نعم' : 'لا';
  if (Array.isArray(value)) return value.map(x => roles[x] || x).join('، ') || '—';
  if (typeof value === 'number' && Number.isFinite(value)) return new Intl.NumberFormat('ar-EG', { maximumFractionDigits: 2 }).format(value);
  const date = typeof value === 'string' && /^\d{4}-\d\d-\d\dT/.test(value) ? new Date(value) : null;
  return date ? new Intl.DateTimeFormat('ar-EG', { dateStyle:'medium', timeStyle:'short' }).format(date) : (roles[value] || String(value));
};
function tokenClaims(token) {
  try { return JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))); } catch { return {}; }
}
function api(path, token, options = {}) {
  return fetch(path, { ...options, headers: { ...(options.body ? {'Content-Type':'application/json'} : {}), ...(token ? { Authorization:`Bearer ${token}` } : {}), ...options.headers } }).then(async response => {
    const body = response.status === 204 ? null : await response.json().catch(() => null);
    if (!response.ok) { const error = new Error(body?.error || body?.message || `تعذر إكمال الطلب (${response.status})`); error.status=response.status; throw error; }
    return body;
  });
}
function Login({ onLogin }) {
  const [busy,setBusy]=useState(false), [error,setError]=useState('');
  async function submit(e){e.preventDefault();setBusy(true);setError('');const fd=new FormData(e.currentTarget);try{const result=await api('/api/Identity/Auth/Login',null,{method:'POST',body:JSON.stringify({usernameOrEmail:fd.get('usernameOrEmail'),password:fd.get('password'),rememberMe:true})});const token=result.accessToken||result.AccessToken;const claims=tokenClaims(token);const claimRole=claims.role||claims['http://schemas.microsoft.com/ws/2008/06/identity/claims/role']||[];const list=Array.isArray(claimRole)?claimRole:[claimRole];if(!list.some(r=>['SuperAdmin','Admin','Pharmacist'].includes(r))){setError('هذا الحساب غير مصرح له بدخول لوحة الإدارة.');return;}sessionStorage.setItem('pharmacy-admin-token',token);onLogin(token,list,claims);}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <main className="login-shell"><section className="login-card"><div className="brand-mark">✚</div><p className="eyebrow">PHARMACY OPERATIONS</p><h1>مرحباً بعودتك</h1><p className="muted">سجّل دخولك إلى مساحة إدارة الصيدلية.</p><form onSubmit={submit}><label>البريد الإلكتروني أو اسم المستخدم<input name="usernameOrEmail" autoComplete="username" required/></label><label>كلمة المرور<input name="password" type="password" autoComplete="current-password" required/></label><button className="button primary wide" disabled={busy}>{busy?'جارٍ تسجيل الدخول…':'تسجيل الدخول'}</button>{error&&<p className="form-error">{error}</p>}</form></section></main>;
}
function App(){
  const [token,setToken]=useState(()=>sessionStorage.getItem('pharmacy-admin-token')),[userRoles,setUserRoles]=useState([]),[claims,setClaims]=useState({}),[page,setPage]=useState(location.hash.slice(1)||'dashboard'),[loading,setLoading]=useState(false),[error,setError]=useState(''),[data,setData]=useState(null),[query,setQuery]=useState(''),[modal,setModal]=useState(null),[toast,setToast]=useState(''),[mobileNav,setMobileNav]=useState(false);
  useEffect(()=>{if(token&&!userRoles.length){const c=tokenClaims(token);const r=c.role||c['http://schemas.microsoft.com/ws/2008/06/identity/claims/role']||[];const list=Array.isArray(r)?r:[r];if(list.some(x=>['SuperAdmin','Admin','Pharmacist'].includes(x))){setUserRoles(list);setClaims(c)}else logout();}},[token]);
  useEffect(()=>{const fn=()=>setPage(location.hash.slice(1)||'dashboard');window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
  const module=modules.find(m=>m.id===page)||modules[0], definition=definitions[page];
  async function load(){if(!token)return;setLoading(true);setError('');try{const body=await api(page==='dashboard'?'/api/Admin/Home/dashboard':definition?.endpoint,token);let result=unwrap(body);if(page==='categories')result=result?.categories??result;if(!Array.isArray(result)&&page!=='dashboard')result=result?[result]:[];setData(result)}catch(e){if(e.status===404&&page!=='dashboard'){setData([])}else{setError(e.message);setData(null)}}finally{setLoading(false)}}
  useEffect(()=>{if(token&&userRoles.length)load()},[token,userRoles.length,page]);
  useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(id)}},[toast]);
  function logout(){sessionStorage.removeItem('pharmacy-admin-token');setToken(null);setUserRoles([]);setData(null)}
  function navigate(id){location.hash=id;setMobileNav(false);setQuery('')}
  async function mutate(path,method,payload){await api(path,token,{method,...(payload===undefined?{}:{body:JSON.stringify(payload)})});setModal(null);setToast('تم حفظ التغييرات بنجاح');load()}
  async function remove(page,item){if(!window.confirm('سيتم حذف هذا السجل. هل تريد المتابعة؟'))return;const path=page==='products'?`/api/Admin/Products?id=${encodeURIComponent(item.id)}`:page==='customers'?`/api/Admin/Customer/${item.id}`:page==='invoices'?`/api/Admin/SalesInvoices/${item.id}`:`/api/Admin/${page[0].toUpperCase()+page.slice(1)}/${item.id}`;try{await api(path,token,{method:'DELETE'});setToast('تم حذف السجل بنجاح');load()}catch(err){setError(err.message)}}
  if(!token)return <Login onLogin={(t,r,c)=>{setToken(t);setUserRoles(r);setClaims(c)}}/>;
  const displayName=claims.unique_name||claims.name||claims['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name']||'فريق الصيدلية';
  return <div className="app-shell"><aside className={`sidebar ${mobileNav?'open':''}`}><a className="brand" href="#dashboard"><span className="brand-mark">✚</span><span><b>صيدليتي</b><small>لوحة الإدارة</small></span></a><div className="nav-caption">مساحة العمل</div><nav>{modules.map(item=><button key={item.id} className={`nav-item ${page===item.id?'active':''}`} onClick={()=>navigate(item.id)}><item.icon size={18}/><span className="nav-label">{item.title}</span></button>)}</nav><div className="sidebar-bottom"><div className="profile-chip"><span className="avatar">{displayName[0]}</span><span><b>{displayName}</b><small>{userRoles.map(r=>roles[r]||r).join('، ')}</small></span></div><button className="button quiet wide" onClick={logout}><LogOut size={15}/> تسجيل الخروج</button></div></aside>{mobileNav&&<button aria-label="إغلاق القائمة" className="scrim" onClick={()=>setMobileNav(false)}/>}
    <main className="workspace"><header className="topbar"><div className="title-side"><button className="menu-button" onClick={()=>setMobileNav(!mobileNav)}><Menu size={20}/></button><div><p className="eyebrow">مساحة العمل / {module.title}</p><h1>{module.title}</h1></div></div><div className="top-actions"><span className="connection"><i/> متصل بالـ API</span><button className="icon-button" title="تحديث البيانات" onClick={load}><RefreshCw size={17}/></button></div></header>{error&&<div className="notice"><ShieldCheck size={16}/>{error}{error.includes('502')||error.includes('تعذر')?' — تأكد من تشغيل الـ API وقاعدة البيانات.':''}<button onClick={load}>إعادة المحاولة</button></div>}<section>{page==='dashboard'?<Dashboard data={data} loading={loading} navigate={navigate}/>:definition?<ResourcePage key={page} page={page} definition={definition} data={data} loading={loading} query={query} setQuery={setQuery} roles={userRoles} onDetail={item=>setModal({type:'detail',item})} onCreate={()=>setModal({type:'create'})} onEdit={item=>setModal({type:'edit',item})} onDelete={item=>remove(page,item)} onLock={item=>mutate(`/api/Admin/Users/${item.id}/${item.isLocked?'unlock':'lock'}`,'PUT')} onOrder={item=>setModal({type:'order',item})}/>:<div className="panel empty">اختر قسماً من القائمة.</div>}</section></main>
    {modal&&<Editor modal={modal} page={page} roles={userRoles} token={token} onClose={()=>setModal(null)} onSave={mutate}/>}<div className={`toast ${toast?'show':''}`}>{toast}</div>
  </div>;
}
function Dashboard({data,loading,navigate}){
  const metrics=[['إجمالي المبيعات',data?.totalSales,'جنيه',ChartNoAxesCombined],['الطلبات',data?.totalOrders,'طلب',ClipboardList],['المنتجات',data?.totalProducts,'منتج',Package],['العملاء',data?.totalCustomers,'عميل',ContactRound],['التشغيلات',data?.totalProductBatches,'تشغيلة',Boxes],['فواتير المبيعات',data?.totalSalesInvoices,'فاتورة',FileText],['المستخدمون',data?.totalUsers,'مستخدم',Users],['طلبات معلقة',data?.pendingOrders,'طلب',Activity]];
  const statuses=[['قيد الانتظار',data?.pendingOrders],['قيد التجهيز',data?.processingOrders],['مكتملة',data?.completedOrders],['ملغاة',data?.cancelledOrders]],max=Math.max(...statuses.map(x=>x[1]||0),1);
  if(loading&&!data)return <div className="loading panel">جارٍ تحميل مؤشرات الصيدلية…</div>;
  if(!data)return <div className="empty panel">لا توجد بيانات للعرض.</div>;
  return <><div className="stats-grid">{metrics.map(([label,value,unit,Icon])=><article className="stat-card" key={label}><div className="stat-head"><span>{label}</span><span className="stat-icon"><Icon size={17}/></span></div><div className="stat-value">{value==null?'—':new Intl.NumberFormat('ar-EG',{maximumFractionDigits:2}).format(value)}<small>{unit}</small></div></article>)}</div><div className="dashboard-grid"><article className="panel"><h3>حالة الطلبات</h3><div className="status-list">{statuses.map(([label,count])=><div className="status-row" key={label}><span>{label}</span><div className="status-track"><div className="status-fill" style={{width:`${Math.max(4,(count||0)/max*100)}%`}}/></div><b>{count??0}</b></div>)}</div></article><article className="panel"><h3>الوصول السريع</h3><div className="quick-links">{[['orders','متابعة الطلبات'],['products','إدارة المنتجات'],['batches','المخزون'],['chats','دعم العملاء']].map(([id,label])=><button className="quick-link" onClick={()=>navigate(id)} key={id}>{label}<span> ←</span></button>)}</div></article></div></>;
}
function ResourcePage({page,definition,data,loading,query,setQuery,roles,onDetail,onCreate,onEdit,onDelete,onLock,onOrder}){
  const writable=(canManage(roles)&&['products','categories','batches','customers','users'].includes(page))||page==='invoices';
  const rows=useMemo(()=>Array.isArray(data)?data.filter(row=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase())):[],[data,query]);
  const canEdit=writable&&definition.editable&&(page!=='categories'||roles.includes('SuperAdmin'));
  const canDelete=(page==='invoices'||(canManage(roles)&&['products','batches','customers'].includes(page))||(page==='categories'&&roles.includes('SuperAdmin')));
  return <><div className="page-heading"><div><h2>{definition.title}</h2><p className="muted">بيانات مباشرة من نظام الصيدلية</p></div>{writable&&<button className="button primary" onClick={onCreate}>＋ إضافة جديد</button>}</div><div className="table-panel"><div className="table-tools"><span className="muted">{rows.length} سجل</span><label className="search-wrap"><Search size={15}/><input className="search" placeholder="ابحث في السجلات…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{loading?<div className="loading">جارٍ تحميل البيانات…</div>:!data?.length?<div className="empty">لا توجد سجلات متاحة حالياً.</div>:<div className="table-wrap"><table><thead><tr>{definition.fields.map(([,label])=><th key={label}>{label}</th>)}<th>إجراء</th></tr></thead><tbody>{rows.map((row,index)=><tr key={row.id??index}>{definition.fields.map(([key])=><td key={key}>{key==='status'?<span className={`badge ${row[key]===2?'green':row[key]===3?'red':row[key]===0?'orange':''}`}>{statusName(row[key])}</span>:key==='isLocked'?<span className={`badge ${row[key]?'red':'green'}`}>{row[key]?'موقوف':'نشط'}</span>:fmt(row[key])}</td>)}<td><div className="row-actions">{definition.detail&&<button className="table-link" onClick={()=>page==='orders'?onOrder(row):onDetail(row)}>عرض التفاصيل</button>}{page==='users'&&<button className="table-link" onClick={()=>onLock(row)}>{row.isLocked?'تفعيل':'إيقاف'}</button>}{canEdit&&<button className="table-link" onClick={()=>onEdit(row)}>تعديل</button>}{canDelete&&<button className="table-link danger" onClick={()=>onDelete(row)}>حذف</button>}</div></td></tr>)}</tbody></table></div>}</div></>;
}
function statusName(v){return ({0:'قيد الانتظار',1:'قيد التجهيز',2:'مكتمل',3:'ملغي'})[v]??fmt(v)}
function Editor({modal,page,roles,token,onClose,onSave}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[invoiceTarget,setInvoiceTarget]=useState('customer');
  const record=modal.item||{};
  async function submit(e){e.preventDefault();setBusy(true);setError('');const fd=new FormData(e.currentTarget);const val=k=>fd.get(k);const num=k=>Number(val(k));let path='',method='POST',payload={};
    if(modal.type==='detail'){return onClose()}
    if(modal.type==='order'){payload={status:num('status'),discount:record.discount||0,deliveryFees:record.deliveryFees||0,deliveryAddress:record.deliveryAddress||'',paymentMethod:record.paymentMethod,applicationUserId:record.applicationUserId};path=`/api/Admin/Orders/${record.id}`;method='PUT'}
    else if(page==='products'){path='/api/Admin/Products';method=modal.type==='edit'?'PUT':'POST';if(method==='PUT')path+=`/${record.id}`;payload={name:val('name'),genericName:val('genericName')||null,price:num('price'),minStockLevel:num('minStockLevel'),requiresPrescription:fd.has('requiresPrescription'),categoryId:num('categoryId')}}
    else if(page==='categories'){path='/api/Admin/Categories';method=modal.type==='edit'?'PUT':'POST';if(method==='PUT')path+=`/${record.id}`;payload={name:val('name')}}
    else if(page==='batches'){path='/api/Admin/Batches';method=modal.type==='edit'?'PUT':'POST';if(method==='PUT')path+=`/${record.id}`;payload={productId:num('productId'),batchNumber:val('batchNumber'),expiryDate:val('expiryDate'),costPrice:num('costPrice'),quantityOnHand:num('quantityOnHand')}}
    else if(page==='customers'){path='/api/Admin/Customers'+(modal.type==='edit'?`/${record.id}`:'/create');method=modal.type==='edit'?'PUT':'POST';payload={name:val('name'),phone:val('phone')||null,...(method==='POST'?{currentBalance:num('currentBalance')}: {})}}
    else if(page==='users'){path='/api/Admin/Users'+(modal.type==='edit'?`/${record.id}`:'');method=modal.type==='edit'?'PUT':'POST';payload={firstName:val('firstName'),lastName:val('lastName'),email:val('email'),phoneNumber:val('phoneNumber')||null,address:val('address')||null,selectedRoles:[...fd.getAll('selectedRoles')],...(val('password')?{password:val('password'),confirmPassword:val('confirmPassword')}:{})};if(method==='POST'){payload.password=val('password');payload.confirmPassword=val('confirmPassword')}}
    else if(page==='invoices'){path='/api/Admin/SalesInvoices/create';payload={invoiceNumber:val('invoiceNumber'),discount:num('discount'),customerId:invoiceTarget==='customer'?num('customerId'):null,orderId:invoiceTarget==='order'?num('orderId'):null,invoiceItems:[{productBatchId:num('productBatchId'),quantity:num('quantity')}]}}
    try{await onSave(path,method,payload)}catch(err){setError(err.message)}finally{setBusy(false)}}
  function field(name,label,value='',type='text',opts={}){return <label key={name} className={`field ${opts.full?'full':''}`}>{label}{type==='select'?<select name={name} value={name==='invoiceTarget'?invoiceTarget:undefined} defaultValue={name==='invoiceTarget'?undefined:value??''} onChange={name==='invoiceTarget'?e=>setInvoiceTarget(e.target.value):undefined} required={opts.required!==false}>{opts.options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:type==='textarea'?<textarea name={name} defaultValue={value??''}/>:type==='checkbox'?<span className="check-field"><input name={name} type="checkbox" defaultChecked={!!value}/>{label}</span>:<input name={name} type={type} defaultValue={value??''} required={!!opts.required} min={opts.min} step={opts.step}/>}</label>}
  let title=modal.type==='detail'?'التفاصيل':modal.type==='order'?'تحديث حالة الطلب':modal.type==='edit'?'تعديل البيانات':'إضافة سجل';
  if(modal.type==='detail')return <dialog open className="modal"><div className="dialog-card"><button className="dialog-close" onClick={onClose}><X/></button><h2>{page==='chats'?'محادثة العميل':page==='invoices'?'تفاصيل الفاتورة':'تفاصيل الطلب'}</h2>{page==='chats'?<ChatDetail id={record.id} token={token}/>:<DetailView page={page} record={record} token={token}/>}<div className="dialog-actions"><button className="button quiet" onClick={onClose}>إغلاق</button></div></div></dialog>;
  return <dialog open className="modal"><form className="dialog-card" onSubmit={submit}><button type="button" className="dialog-close" onClick={onClose}><X/></button><h2>{title}</h2><div className="form-grid">
    {modal.type==='order'&&<><p className="muted full">تعتمد الحالات المتاحة على حالة السداد وقواعد سير الطلب، وسيرفض الـ API أي انتقال غير مسموح.</p>{field('status','حالة الطلب',record.status,'select',{options:[[0,'قيد الانتظار'],[1,'قيد التجهيز'],[2,'مكتمل'],...(record.status===3?[[3,'ملغي (الحالة الحالية)']]:[])]})}</>}
    {page==='products'&&<>{field('name','اسم المنتج',record.name,'text',{required:true})}{field('genericName','الاسم العلمي',record.genericName)}{field('price','السعر',record.price,'number',{required:true,min:0,step:'0.01'})}{field('minStockLevel','حد المخزون',record.minStockLevel??5,'number',{required:true,min:0})}<LookupSelect token={token} name="categoryId" label="التصنيف" endpoint="/api/Admin/Categories" value={record.categoryId} itemLabel={x=>x.name}/>{field('requiresPrescription','يتطلب وصفة طبية',record.requiresPrescription,'checkbox')}</>}
    {page==='categories'&&field('name','اسم التصنيف',record.name,'text',{required:true})}
    {page==='batches'&&<><LookupSelect token={token} name="productId" label="المنتج" endpoint="/api/Admin/Products/get" value={record.productId} itemLabel={x=>x.genericName?`${x.name} — ${x.genericName}`:x.name}/>{field('batchNumber','رقم التشغيلة',record.batchNumber,'text',{required:true})}{field('expiryDate','تاريخ الصلاحية',record.expiryDate?.slice(0,10)||'','date',{required:true})}{field('costPrice','سعر التكلفة',record.costPrice,'number',{required:true,min:0,step:'0.01'})}{field('quantityOnHand','الكمية المتاحة',record.quantityOnHand,'number',{required:true,min:0})}</>}
    {page==='customers'&&<>{field('name','اسم العميل',record.name,'text',{required:true})}{field('phone','رقم الهاتف',record.phone)}{modal.type==='create'&&field('currentBalance','الرصيد الافتتاحي','0','number',{min:0,step:'0.01'})}</>}
    {page==='users'&&<>{field('firstName','الاسم الأول',record.firstName,'text',{required:true})}{field('lastName','اسم العائلة',record.lastName,'text',{required:true})}{field('email','البريد الإلكتروني',record.email,'email',{required:true})}{field('phoneNumber','الهاتف',record.phoneNumber)}{field('address','العنوان',record.address,'text')}{modal.type==='create'&&<>{field('password','كلمة المرور','','password',{required:true})}{field('confirmPassword','تأكيد كلمة المرور','','password',{required:true})}</>}<div className="field full"><span>الأدوار</span><RolePicker token={token} selected={record.roles||[]}/></div></>}
    {page==='invoices'&&<>{field('invoiceNumber','رقم الفاتورة','','text',{required:true})}{field('discount','الخصم','0','number',{min:0,step:'0.01'})}{field('invoiceTarget','نوع الفاتورة',invoiceTarget,'select',{options:[['customer','عميل'],['order','طلب']]})}{invoiceTarget==='customer'?<LookupSelect token={token} name="customerId" label="العميل" endpoint="/api/Admin/Customer/get" itemLabel={x=>`${x.name}${x.phone?` — ${x.phone}`:''}`}/>:<LookupSelect token={token} name="orderId" label="الطلب" endpoint="/api/Admin/Orders" itemLabel={x=>x.orderNumber}/>}<LookupSelect token={token} name="productBatchId" label="تشغيلة المنتج" endpoint="/api/Admin/Batches" itemLabel={x=>`${x.productName} — ${x.batchNumber} (${x.quantityOnHand} متاح)`}/>{field('quantity','الكمية','1','number',{required:true,min:1})}</>}
    {error&&<div className="form-error-block full">{error}</div>}
  </div><div className="dialog-actions"><button className="button primary" disabled={busy}>{busy?'جارٍ الحفظ…':'حفظ'}</button><button type="button" className="button quiet" onClick={onClose}>إلغاء</button></div></form></dialog>;
}
function RolePicker({token,selected}){const[roles,setRoles]=useState([]);useEffect(()=>{api('/api/Admin/Users/roles',token).then(x=>setRoles(unwrap(x)||[])).catch(()=>setRoles(['Admin','Pharmacist']))},[token]);return <div className="role-options">{roles.filter(r=>['Admin','Pharmacist','Customer'].includes(r)).map(role=><label key={role}><input name="selectedRoles" type="checkbox" value={role} defaultChecked={selected.includes(role)}/>{rolesMap(role)}</label>)}</div>}
function LookupSelect({token,name,label,endpoint,value,itemLabel}){const[items,setItems]=useState([]),[error,setError]=useState('');useEffect(()=>{let active=true;api(endpoint,token).then(body=>{let data=unwrap(body);if(data?.categories)data=data.categories;if(active)setItems(Array.isArray(data)?data:[])}).catch(()=>{if(active)setError('تعذر تحميل الخيارات')});return()=>{active=false}},[endpoint,token]);return <label className="field">{label}<select name={name} defaultValue={value??''} required disabled={!items.length}><option value="">{error||(!items.length?'جارٍ تحميل الخيارات…':'اختر…')}</option>{items.map(item=><option value={item.id} key={item.id}>{itemLabel(item)}</option>)}</select></label>}
function rolesMap(role){return roles[role]||role}
function DetailView({page,record,token}){const[details,setDetails]=useState(null),[error,setError]=useState('');useEffect(()=>{const endpoint=page==='orders'?`/api/Admin/Orders/${record.id}`:`/api/Admin/SalesInvoices/${record.id}`;api(endpoint,token).then(x=>setDetails(unwrap(x))).catch(e=>setError(e.message))},[page,record.id,token]);if(error)return <div className="form-error-block">{error}</div>;if(!details)return <div className="loading">جارٍ تحميل التفاصيل…</div>;return <div className="detail-stack">{Object.entries(details).filter(([k,v])=>!['orderItems','invoiceItems'].includes(k)&&v!==null&&typeof v!=='object').map(([k,v])=><div className="detail-line" key={k}><span>{labels[k]||k}</span><b>{fmt(v)}</b></div>)}{(details.orderItems||details.invoiceItems||[]).length>0&&<><h3>الأصناف</h3>{(details.orderItems||details.invoiceItems).map((item,i)=><div className="detail-line" key={i}><span>{item.productId?`منتج ${item.productId}`:`تشغيلة ${item.productBatchId}`} · {fmt(item.quantity)} × {fmt(item.unitPrice)}</span><b>{fmt(item.totalPrice)}</b></div>)}</>}</div>}
function ChatDetail({id,token}){const[data,setData]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[sending,setSending]=useState(false),[connection,setConnection]=useState(null);useEffect(()=>{let active=true;api(`/api/Admin/Chat/${id}`,token).then(x=>{if(active)setData(unwrap(x))}).catch(e=>{if(active)setError(e.message)});const hub=new HubConnectionBuilder().withUrl('/hubs/chat',{accessTokenFactory:()=>token,transport:HttpTransportType.WebSockets|HttpTransportType.LongPolling}).withAutomaticReconnect().configureLogging(LogLevel.Error).build();hub.on('ReceiveMessage',msg=>{if(msg.chatId===id)setData(current=>current?{...current,messages:[...(current.messages||[]).filter(x=>x.id!==msg.id),msg]}:current)});hub.start().then(()=>hub.invoke('JoinChat',id)).then(()=>{if(active)setConnection(hub)}).catch(e=>{if(active)setError(previous=>previous||`تعذر الاتصال المباشر بالمحادثة: ${e.message}`)});return()=>{active=false;hub.stop()}},[id,token]);async function send(e){e.preventDefault();const text=message.trim();if(!text||!connection)return;setSending(true);try{await connection.invoke('SendMessage',id,text);setMessage('')}catch(e){setError(e.message)}finally{setSending(false)}}if(error)return <div className="form-error-block">{error}</div>;if(!data)return <div className="loading">جارٍ تحميل المحادثة…</div>;return <div className="dialog-body"><p>العميل: {data.customerName}</p><div className="chat-messages">{data.messages?.length?data.messages.map(m=><article className={`message-row ${m.senderId===data.adminId?'mine':''}`} key={m.id}><p>{m.message}</p><small>{fmt(m.sentAt)}</small></article>):<p className="muted">لا توجد رسائل.</p>}</div><form className="reply-form" onSubmit={send}><input value={message} maxLength={1000} onChange={e=>setMessage(e.target.value)} placeholder="اكتب ردك للعميل…" required/><button className="button primary" disabled={!connection||sending||!message.trim()}>{sending?'إرسال…':'إرسال'}</button></form>{!connection&&<small className="muted">جارٍ فتح الاتصال المباشر…</small>}</div>}
const labels={id:'المعرف',orderNumber:'رقم الطلب',orderDate:'تاريخ الطلب',status:'الحالة',isPaid:'مدفوع',totalAmount:'الإجمالي',discount:'الخصم',deliveryFees:'التوصيل',netAmount:'الصافي',paymentMethod:'طريقة الدفع',deliveryAddress:'العنوان',notes:'ملاحظات',applicationUserId:'معرف العميل',invoiceNumber:'رقم الفاتورة',invoiceDate:'التاريخ',customerId:'العميل',orderId:'الطلب'};
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
